version: '2'
services:

  proxy:
    image: "nginx"
    restart: always
    container_name: "clustermanager_proxy"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    networks:
      - main

  application:
    container_name: "clustermanager_application"
    image: "davidevitelaru/clustermanager:0.1.0.39-docker"
    restart: always
    ports:
     - "5000:5000"
    networks:
     - main
    environment:
     - CM_DB_URI=mongodb://mongodb/

  database:
    image: "mongo"
    container_name: "clustermanager_mongodb"
    restart: always
    ports:
     - "27017:27017"
    networks:
     - main

networks:
  main:
    driver: bridge
